name: Unzip File

on:
  push:
    paths:
      - '**.zip'  # Triggers when a ZIP file is pushed

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Unzip File
        run: unzip file.zip -d extracted_files
